### ISSUE TITLE
Show Fink version in UI

### ISSUE THREAD

**Issue by NiklasBuchfink** [opral/inlang-fink#9]
## Context

When issues come up for Fink:

1. We can't roll back to an older version
2. It is difficult for us to understand since which version this problem exists
3. Fink always uses the newest version of lix and the inlang-message-sdk after updates are merged

## Proposal

- [ ] Version Fink [FINK-5](https://linear.app/opral/issue/FINK-5/move-fink-manage-and-badge-to-changeset-based-deployment) 
- [ ] Display the current version in the UI

**Comment by NiklasBuchfink** [comment]
@jan.johannes @jldec Does that meet your expectations?
And is the Fink changeset version enough or would you like to see the message-sdk & lix version as well?

**Comment by jldec** [comment]
- commit sha of the deployed fink service would be super-useful
- version number of the fink package is also nice (easier for humans) but slightly less useful since it may not necessarily have changed for each deploy. 
- expando/dropdown with dependent (sdk + lix) versions or a link tothe build on github would be useful too
